---
author: "黃柏勳 310708003 交大科管 "
title: "練習題"
date: |
  | 2022-06-02
output:
  html_document:
    number_sections: no
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = '#>',error=TRUE, results = 'hold', out.width='70%', fig.align = 'center')
```

## 練習題

請將 data.csv[^src] 讀入成一個 data frame，並：

1. 請刪除重複的資料
1. 請使用105-108年的資料
1. 請將各縣市各年各月份的垃圾產生量 `GarbageGenerated` 製作成各縣市年度總垃圾量`TotalGarbage`摘要表
1. 將請寫一個函數分類各縣市所在的區域，並為摘要表新增區域`region`欄位
1. 繪出以各縣市為x軸座標，以`TotalGarbage`為y軸，並以年份為facet，用顏色標示區域`region`

[^src]: 資料來源：https://data.gov.tw/dataset/89022


```{r}
# 讀取資料
library(readr)
data <- read_csv("C:/Users/huang/Rlads/exercise/data.csv")
```


```{r}
# 分類縣市函數
library(dplyr)

as_region <- function(country){
  region <- sapply(country, function(x){
    if (x %in% c("臺北市", "新北市", "基隆市", "桃園市", "新竹市", "新竹縣", "宜蘭縣")) 
        return("北部")
    if (x %in% c("苗栗縣", "臺中市", "彰化縣", "南投縣", "雲林縣"))
        return("中部")
    if (x %in% c("嘉義市", "嘉義縣", "臺南市", "高雄市", "屏東縣", "澎湖縣"))
        return("南部")
    if (x %in% c("花蓮縣", "臺東縣")) 
        return("東部")
    return("離島")
  })
  return(region)
}

# 資料整理
Garbage_cleaned<- data %>%
  distinct() %>%
  filter(year != 109) %>%
  group_by(year, county) %>%
  summarise(TotalGarbage = sum(GarbageGenerated)) %>%
  ungroup() %>%
  mutate(region = as_region(county))
Garbage_cleaned  
#助教解
#分類縣市函數
#cls <- list(
#   island = "金門縣 連江縣 澎湖縣",
#   north = "基隆市 新北市 臺北市 桃園市 新竹縣 新竹市 宜蘭縣",
#   center = "苗栗縣 臺中市 彰化縣 雲林縣 南投縣",
#   south = "嘉義縣 嘉義市 臺南市 高雄市 屏東縣",
#   east = "花蓮縣 臺東縣"
#)
#cls <- lapply(cls, function(x) strsplit(x, " ")[[1]])

#region_atom <- function(x) {
#   for (name in names(cls))
#      if (x %in% cls[[name]]) return(name)
#   return(NULL)
#}
#region <- function(x) {
#   results <- sapply(x, region_atom, USE.NAMES = F)
#   return(results)
#}

# 資料整理
#garbage_by_region <- df %>%
#   distinct() %>%
#   filter(year %in% 105:108) %>%
#   group_by(year, county) %>%
#   summarise(TotalGarbage = sum(GarbageGenerated)) %>%
#   ungroup() %>%
#   mutate(region = region(county))
```

```{r}
# 視覺化
library(ggplot2)
ggplot(Garbage_cleaned) +
  geom_bar(aes(x = county, y = TotalGarbage, fill = region), stat = "identity") +
  facet_wrap(vars(year)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 5))

#助教解
#theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```
